# Generated by Django 3.0 on 2019-12-15 05:40

from django.db import migrations, models
import dq.functions


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0003_auto_20191214_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdl',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=dq.functions.get_uploaded_cdl_file_name),
        ),
    ]
