# Generated by Django 3.0 on 2019-12-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0005_medical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical',
            options={'ordering': ['date_issue']},
        ),
        migrations.CreateModel(
            name='DrugTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pre Employment', 'Pre Employment'), ('Random', 'Random'), ('Post Accident', 'Post Accident'), ('Reasonable Suspicion', 'Reasonable Suspicion')], max_length=100, null=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('date_results', models.DateField(blank=True, null=True)),
                ('results', models.CharField(blank=True, choices=[('NEGATIVE', 'NEGATIVE'), ('POSITIVE', 'POSITIVE')], max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dq.Person')),
            ],
            options={
                'ordering': ['date_results'],
            },
        ),
    ]
