# Generated by Django 3.0 on 2019-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0006_auto_20191223_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdl',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Surrendered', 'Surrendered'), ('Suspended', 'Suspended'), ('Invalid', 'Invalid')], max_length=100, null=True),
        ),
    ]
