# Generated by Django 3.0 on 2019-12-27 06:45

from django.db import migrations
import dq.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0007_cdl_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdl',
            name='status',
        ),
        migrations.AddField(
            model_name='cdl',
            name='isactive',
            field=dq.fields.UniqueBooleanFieldTrue(default=False),
        ),
    ]
