# Generated by Django 3.0 on 2019-12-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0008_auto_20191227_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdl',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
